server:
  port: 8080
  servlet:
    context-path: /fctest

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:8079/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true